apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: 0.7.19
    helm:
      values: |
        service:
          type: ClusterIP

        ingress:
          enabled: false

        backendStore:
          databaseMigration: true
          postgres:
            enabled: true
            host: postgres-postgresql.application.svc.cluster.local
            port: 5432
            database: mlflow
            user: mlflow
            password: mlflow123

        artifactRoot:
          s3:
            enabled: true
            bucket: mlflow-artifacts
            awsAccessKeyId: admin
            awsSecretAccessKey: admin12345

        extraEnvVars:
          MLFLOW_S3_ENDPOINT_URL: http://minio.application.svc.cluster.local:9000
          AWS_DEFAULT_REGION: us-east-1
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
